# Generated by Django 5.0.2 on 2024-02-21 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "post_id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name=uuid.uuid4,
                    ),
                ),
                ("post_title", models.CharField(max_length=300)),
                ("post_description", models.TextField()),
                ("post_posted_date", models.DateField(auto_now_add=True)),
                ("post_last_updated_date", models.DateField(auto_now=True)),
                ("post_uploaded_time", models.TimeField(auto_now_add=True)),
                ("post_last_uploaded_time", models.TimeField(auto_now=True)),
                ("post_image_link", models.ImageField(upload_to="posts/")),
                (
                    "post_author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
