# Generated by Django 4.2.11 on 2024-06-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_at_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_author',
        ),
    ]
