# Generated by Django 5.0.2 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_rename_comment_like_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ManyToManyField(related_name="likes", to="posts.post"),
        ),
    ]
